name: API Key Workflow

on:
  push:
    branches:
      - main  # Run on push to the main branch
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  use_api_keys:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Display Environment Variables (safe output)
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
        run: |
          echo "Using Google API Key (safe output)"
          echo "Using TMDB API Token (safe output)"

      - name: API Call to TMDB without Authorization Header
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          # Making the request with only the API key, which TMDB typically requires
          curl --http1.1 -v "https://api.themoviedb.org/3/movie/popular?api_key=$GOOGLE_API_KEY"

      - name: Debugging Example API Call with Bearer Token (if needed)
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
        run: |
          # Debugging call with Authorization header in case it's required for other APIs
          curl --http1.1 -v -H "Authorization: Bearer $TMDB_API_TOKEN" "https://api.themoviedb.org/3/movie/popular?api_key=$GOOGLE_API_KEY"
